# File              : install.yml
# Author            : Rustam Khafizov <super.rustamm@gmail.com>
# Date              : 06.09.2020
# Last Modified Date: 07.09.2020
# Last Modified By  : Rustam Khafizov <super.rustamm@gmail.com>

---
- name: updating before start
  become: true
  apt:
    update_cache: true
    cache_valid_time: 0
    force_apt_get: true
    upgrade: dist

- name: installing dependencies
  become: true
  apt:
    name: "{{ item }}"
    state: latest
  loop: "{{ dependencies }}"

- name: uninstalling all other vims
  become: true
  apt:
    name: "{{ item }}"
    state: absent
  loop: "{{ other_vims }}"

- name: downloading vim and vim configuration
  become: true
  git:
    repo: "{{ item.url }}"
    dest: "/tmp/{{ item.name }}"
  loop:
    - url: "https://github.com/vim/vim.git"
      name: vim
    - url: "https://github.com/amix/vimrc.git"
      name: vimrc

- name: configuring vim compile
  become: true
  shell:
    cmd: |
      cd /tmp/vim && ./configure {{ configure_opts }}
    warn: false

- name: installing vim
  become: true
  shell:
    cmd: |
      cd /tmp/vim                                   && \
      make VIMRUNTIMEDIR=/usr/local/share/vim/vim82 && \
      make install
    warn: false
