# File              : main.yml
# Author            : Rustam Khafizov <super.rustamm@gmail.com>
# Date              : 06.09.2020
# Last Modified Date: 06.09.2020
# Last Modified By  : Rustam Khafizov <super.rustamm@gmail.com>

---
- name: installing...
  include_tasks: install.yml
  when: state == 'install'

- name: configuring...
  include_tasks: configure.yml
  when: state == 'install'

- name: uninstalling
  include_tasks: uninstall.yml
  when: "'uninstall' in state"
