# File              : main.yml
# Author            : Rustam Khafizov <super.rustamm@gmail.com>
# Date              : 06.09.2020
# Last Modified Date: 12.09.2020
# Last Modified By  : Rustam Khafizov <super.rustamm@gmail.com>

---
